### ISSUE TITLE
accelerator_acxiom_dataretrieval.md instructions state files that are not find in source

### ISSUE THREAD

**Issue by lawndale5** [IBM-i2/Data-Acquisition-Accelerators#1]
In the below instructions artifacts directory is missing??

Deploy the Counter Fraud schema in your new Developer Essentials deployment.

Copy the files counter-fraud-schema.xml and counter-fraud-schema-charting-schemes.xml from the Acxiom_Accelerator\artifacts directory in the downloaded folder, into the directory IAP-Deployment-Toolkit\configuration\fragments\common\WEB-INF\classes.

**Comment by boalesth** [comment]
Hi there, 

Thanks for pointing this out, I've added the missing files for you.

Kind regards

Esther
