### ISSUE TITLE
Configuring the data retrieval components of the IBM i2 Accelerator for Acxiom IDOD STEP #11

### ISSUE THREAD

**Issue by lawndale5** [IBM-i2/Data-Acquisition-Accelerators#2]
python da-setup.py -t add-daod-data-source -a acxiomread -d acxiom-example

When I execute the above command receive this error:

c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts>python da-setup.py -t add-daod-data-source -a acxiomread -d acxiom-examp
le
Logging to c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\configuration\logs\2015_07_15__06_42_30__da__add-daod-data-source.log
...

Buildfile: c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts\da-setup.xml

add-daod-data-source:
     [copy] Copying 1 file to c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\configuration\fragments\acxiom-example
    [mkdir] Created dir: c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\application\temp\schema-converter-temp\java
    [mkdir] Created dir: c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\application\temp\schema-converter-temp\output
     [exec]
     [exec] warning: The apt tool and its associated API are planned to be
     [exec] removed in the next major JDK release.  These features have been
     [exec] superseded by javac and the standardized annotation processing API,
     [exec] javax.annotation.processing and javax.lang.model.  Users are
     [exec] recommended to migrate to the annotation processing features of
     [exec] javac; see the javac man page for more information.
     [exec] Note: Writing c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts\schema1.xsd
     [exec] Note: Writing c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts\schema2.xsd
     [exec] Note: Writing c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts\schema3.xsd
     [exec] Note: Writing c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts\schema4.xsd
      [jar] Building jar: c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\configuration\fragments\acxiom-example\WEB-INF\lib\cou
nter-fraud-schema.jar
   [delete] Deleting directory c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\application\temp\schema-converter-temp
     [xslt] Processing c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\configuration\environment\topology.xml to c:\IBM\iap-3.0.
9\IAP-Deployment-Toolkit\configuration\environment\topology_Temp.xml
     [xslt] Loading stylesheet c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts\common\topology-xml-add-data-source-fragm
ent-with-flags.xsl

BUILD FAILED
c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts\da-setup.xml:136: The following error occurred while executing this line
:
c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts\da-setup.xml:207: The following error occurred while executing this line
:
c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts\da-setup.xml:268: The following error occurred while executing this line
:
c:\IBM\iap-3.0.9\IAP-Deployment-Toolkit\scripts\common\existence-checks.xml:19: Property 'apollo.data' has not been set

~~~~~~~~

I opened up existence-checks.xml and can't find 'apollo.data'.

**Comment by boalesth** [comment]
Hi there,
Have you configured your environment settings by following the instructions in the deployment guide?

http://www.ibm.com/support/docview.wss?uid=swg27041249&aid=3

apollo.data is found in IAP-Deployment-Toolkit\
configuration\environment\write\environment.properties

Thanks 
Esther

**Comment by lawndale5** [comment]
I looked in that file I have that set to
################################################################################
# Temporary storage

# The path to a directory where the Intelligence Analysis Platform can store
# temporary files.
# For example, C:/iap-data on Windows, or /iap-data on Linux
apollo.data=C:/iap-data

Also I was able to finish the dataretrieval portion successfully for domaintools getting past this similar step.

**Comment by boalesth** [comment]
Hi Lawndale,

Sorry my path was incorrect, as you are creating a new fragment, you need to specify the apollo.data property in IAP-Deployment-Toolkit\configuration\environment\acxiomread\environment.properties 

Thanks

Esther

**Comment by lawndale5** [comment]
So that file has other props that need to be set to correct? Like was, java, db2 etc. which I see are all blank.  It should be same values as what is set in IAP-Deployment-Toolkit\configuration\environment\read\environment.properties correct?

**Comment by boalesth** [comment]
Hi Lawnsdale,

Yup, that should be populated in the same way as the write version.

Thanks
Esther
