### ISSUE TITLE
Configuring the data retrieval components of the IBM i2 Accelerator for Acxiom IDOD STEP 22

### ISSUE THREAD

**Issue by lawndale5** [IBM-i2/Data-Acquisition-Accelerators#3]
When I add the IAP-Deployment-Toolkit\SDK\sdk-projects\acxiom-example directory to Eclipse I see the compile errors due to missing files in package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response (IAP-Deployment-Toolkit\SDK\sdk-projects\acxiom-example\src\acxiom-soap\com\acxiom\schemas\v201110\us\idod\comprehensivereport\response):

AssociateRelativeNameAddressData.java
ComprehensiveNameAddressPropertyInfo.java
HigherEducationRestrictedUseType.java
PeopleAssociativeRestrictedUseInfo.java
PeopleContactRestrictedUseInfo.java
PeopleNameAddressRestrictedUseInfo.java

**Comment by garywi** [comment]
Thank you for the information.  We are investigating this issue and will respond as soon as we can.
Regards
Gary

**Comment by lawndale5** [comment]
Any update?

**Comment by garywi** [comment]
The investigation is continuing and we expect to upload a fix today. If not, I will provide an update by close of business UK time today.

**Comment by garywi** [comment]
Testing has completed and some missing files were identified.  These have now been uploaded and you should find that the project will now work as expected.  Apologies for the disruption this may have caused.
Regards
Gary

**Comment by lawndale5** [comment]
I downloaded the new zip and I don't see acxiom-example directory from the Acxiom_Accelerator\eclipse-project? Is it now called domaintools or did you by mistake not upload it?

**Comment by lawndale5** [comment]
Deleted last comment was looking wrong place
